local palette = require("dma_theme.palette")

local M = {}

local function apply_highlights(colors)
  local highlights = {
    Normal = { fg = colors.fg, bg = colors.bg },
    NormalNC = { fg = colors.fg, bg = colors.bg },
    NormalFloat = { fg = colors.fg, bg = colors.bg_alt },
    FloatBorder = { fg = colors.border, bg = colors.bg_alt },
    FloatTitle = { fg = colors.fg, bg = colors.bg_alt, bold = true },

    Cursor = { fg = colors.bg, bg = colors.cursor },
    CursorLine = { bg = colors.bg_alt },
    CursorLineNr = { fg = colors.line_nr_active, bold = true },
    CursorColumn = { bg = colors.bg_alt },
    ColorColumn = { bg = colors.bg_alt },

    LineNr = { fg = colors.line_nr },
    LineNrAbove = { fg = colors.line_nr },
    LineNrBelow = { fg = colors.line_nr },

    SignColumn = { fg = colors.fg_subtle, bg = colors.bg },
    FoldColumn = { fg = colors.fg_subtle, bg = colors.bg },

    Visual = { bg = colors.selection, fg = colors.selection_fg },
    VisualNOS = { bg = colors.selection },

    Search = { bg = colors.diff_add_bg, fg = colors.diff_add_fg },
    IncSearch = { bg = colors.diff_remove_bg, fg = colors.diff_remove_fg },
    CurSearch = { bg = colors.semantic.warning.base, fg = colors.bg },
    Substitute = { bg = colors.semantic.warning.base, fg = colors.bg },

    MatchParen = { fg = colors.cursor, bg = colors.selection, bold = true },

    Comment = { fg = colors.comment, italic = true },
    Todo = { fg = colors.semantic.warning.base, bold = true },
    FIXME = { fg = colors.semantic.error.base, bold = true },
    NOTE = { fg = colors.semantic.info.base, bold = true },

    Constant = { fg = colors.constant },
    String = { fg = colors.string },
    Character = { fg = colors.string },
    Number = { fg = colors.number },
    Boolean = { fg = colors.number },
    Float = { fg = colors.number },

    Identifier = { fg = colors.variable },
    Function = { fg = colors.func },

    Statement = { fg = colors.keyword },
    Conditional = { fg = colors.keyword_control },
    Repeat = { fg = colors.keyword_control },
    Label = { fg = colors.keyword },
    Operator = { fg = colors.operator },
    Keyword = { fg = colors.keyword, bold = true },
    Exception = { fg = colors.keyword },

    PreProc = { fg = colors.annotation },
    Include = { fg = colors.annotation },
    Define = { fg = colors.annotation },
    Macro = { fg = colors.decorator },
    PreCondit = { fg = colors.annotation },

    Type = { fg = colors.type, bold = true },
    StorageClass = { fg = colors.storage },
    Structure = { fg = colors.type, bold = true },
    Typedef = { fg = colors.type, bold = true },

    Special = { fg = colors.escape },
    SpecialChar = { fg = colors.escape },
    Tag = { fg = colors.tag },
    Delimiter = { fg = colors.punctuation },
    SpecialComment = { fg = colors.comment },
    Debug = { fg = colors.semantic.error.base },

    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Strikethrough = { strikethrough = true },

    Error = { fg = colors.semantic.error.base, bg = colors.diff_remove_bg },
    ErrorMsg = { fg = colors.semantic.error.base, bold = true },
    WarningMsg = { fg = colors.semantic.warning.base, bold = true },
    ModeMsg = { fg = colors.fg },
    MoreMsg = { fg = colors.semantic.info.base },
    Question = { fg = colors.semantic.info.base },

    Pmenu = { fg = colors.fg, bg = colors.bg_alt },
    PmenuSel = { fg = colors.fg, bg = colors.selection },
    PmenuSbar = { bg = colors.border },
    PmenuThumb = { bg = colors.fg_subtle },
    PmenuKind = { fg = colors.type },
    PmenuKindSel = { fg = colors.type, bg = colors.selection },
    PmenuExtra = { fg = colors.fg_subtle },
    PmenuExtraSel = { fg = colors.fg_subtle, bg = colors.selection },

    StatusLine = { fg = colors.fg, bg = colors.bg_alt },
    StatusLineNC = { fg = colors.fg_subtle, bg = colors.bg },
    StatusLineTerm = { fg = colors.fg, bg = colors.bg_alt },
    StatusLineTermNC = { fg = colors.fg_subtle, bg = colors.bg },

    TabLine = { fg = colors.fg_subtle, bg = colors.bg_alt },
    TabLineFill = { bg = colors.bg_alt },
    TabLineSel = { fg = colors.fg, bg = colors.bg, bold = true },

    WinSeparator = { fg = colors.border },
    WinBar = { fg = colors.fg, bg = colors.bg_alt },
    WinBarNC = { fg = colors.fg_subtle, bg = colors.bg },

    Directory = { fg = colors.func },
    Title = { fg = colors.markup_heading, bold = true },

    DiffAdd = { bg = colors.diff_add_bg },
    DiffChange = { bg = colors.diff_remove_bg },
    DiffDelete = { bg = colors.diff_remove_bg },
    DiffText = { bg = colors.selection },
    DiffAdded = { fg = colors.git_add },
    DiffRemoved = { fg = colors.git_deleted },
    DiffChanged = { fg = colors.git_modified },
    DiffFile = { fg = colors.func },
    DiffIndexLine = { fg = colors.comment },

    SpellBad = { sp = colors.semantic.error.base, undercurl = true },
    SpellCap = { sp = colors.semantic.warning.base, undercurl = true },
    SpellRare = { sp = colors.semantic.info.base, undercurl = true },
    SpellLocal = { sp = colors.semantic.success.base, undercurl = true },

    DiagnosticError = { fg = colors.semantic.error.base },
    DiagnosticWarn = { fg = colors.semantic.warning.base },
    DiagnosticInfo = { fg = colors.semantic.info.base },
    DiagnosticHint = { fg = colors.semantic.success.base },
    DiagnosticOk = { fg = colors.semantic.success.base },
    DiagnosticVirtualTextError = { fg = colors.semantic.error.base, bg = colors.diff_remove_bg },
    DiagnosticVirtualTextWarn = { fg = colors.semantic.warning.base, bg = colors.diff_remove_bg },
    DiagnosticVirtualTextInfo = { fg = colors.semantic.info.base, bg = colors.selection },
    DiagnosticVirtualTextHint = { fg = colors.semantic.success.base, bg = colors.diff_add_bg },
    DiagnosticUnderlineError = { sp = colors.semantic.error.base, undercurl = true },
    DiagnosticUnderlineWarn = { sp = colors.semantic.warning.base, undercurl = true },
    DiagnosticUnderlineInfo = { sp = colors.semantic.info.base, undercurl = true },
    DiagnosticUnderlineHint = { sp = colors.semantic.success.base, undercurl = true },
    DiagnosticSignError = { fg = colors.semantic.error.base },
    DiagnosticSignWarn = { fg = colors.semantic.warning.base },
    DiagnosticSignInfo = { fg = colors.semantic.info.base },
    DiagnosticSignHint = { fg = colors.semantic.success.base },

    LspReferenceText = { bg = colors.selection },
    LspReferenceRead = { bg = colors.selection },
    LspReferenceWrite = { bg = colors.selection, underline = true },
    LspCodeLens = { fg = colors.comment },
    LspCodeLensSeparator = { fg = colors.comment },
    LspSignatureActiveParameter = { fg = colors.cursor, bold = true },
    LspInlayHint = { fg = colors.fg_subtle, bg = colors.bg_alt },

    TreeSitter = {},
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.error"] = { fg = colors.semantic.error.base },
    ["@comment.warning"] = { fg = colors.semantic.warning.base },
    ["@comment.note"] = { fg = colors.semantic.info.base },
    ["@comment.todo"] = { fg = colors.semantic.warning.base, bold = true },

    ["@string"] = { link = "String" },
    ["@string.documentation"] = { link = "String" },
    ["@string.regexp"] = { fg = colors.regex },
    ["@string.escape"] = { fg = colors.escape, bold = true },
    ["@string.special"] = { fg = colors.special },
    ["@string.special.symbol"] = { fg = colors.constant },
    ["@string.special.url"] = { fg = colors.link, underline = true },

    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },

    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },

    ["@boolean"] = { link = "Boolean" },

    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = colors.constant },
    ["@constant.macro"] = { fg = colors.constant },

    ["@variable"] = { link = "Identifier" },
    ["@variable.builtin"] = { fg = colors.variable, italic = true },
    ["@variable.parameter"] = { fg = colors.parameter },
    ["@variable.parameter.builtin"] = { fg = colors.parameter, italic = true },
    ["@variable.member"] = { fg = colors.property },

    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = colors.func },
    ["@function.call"] = { fg = colors.func },
    ["@function.macro"] = { fg = colors.decorator },
    ["@function.method"] = { fg = colors.method },
    ["@function.method.call"] = { fg = colors.method },

    ["@keyword"] = { link = "Keyword" },
    ["@keyword.coroutine"] = { fg = colors.keyword },
    ["@keyword.function"] = { fg = colors.keyword },
    ["@keyword.operator"] = { fg = colors.operator },
    ["@keyword.import"] = { fg = colors.annotation },
    ["@keyword.type"] = { fg = colors.keyword },
    ["@keyword.modifier"] = { fg = colors.storage },
    ["@keyword.repeat"] = { fg = colors.keyword_control },
    ["@keyword.return"] = { fg = colors.keyword },
    ["@keyword.debug"] = { fg = colors.semantic.error.base },
    ["@keyword.exception"] = { fg = colors.keyword },
    ["@keyword.conditional"] = { fg = colors.keyword_control },
    ["@keyword.conditional.ternary"] = { fg = colors.operator },

    ["@operator"] = { link = "Operator" },

    ["@punctuation"] = { link = "Delimiter" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { fg = colors.bracket },
    ["@punctuation.special"] = { fg = colors.punctuation },

    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = colors.type },
    ["@type.definition"] = { fg = colors.type, bold = true },
    ["@type.qualifier"] = { fg = colors.storage },

    ["@attribute"] = { fg = colors.attribute },
    ["@attribute.builtin"] = { fg = colors.annotation },
    ["@property"] = { fg = colors.property },

    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { fg = colors.attribute },
    ["@tag.delimiter"] = { fg = colors.punctuation },

    ["@module"] = { fg = colors.namespace },
    ["@namespace"] = { fg = colors.namespace },

    ["@label"] = { fg = colors.label },

    ["@markup"] = { fg = colors.fg },
    ["@markup.strong"] = { fg = colors.markup_bold, bold = true },
    ["@markup.emphasis"] = { fg = colors.markup_italic, italic = true },
    ["@markup.strikethrough"] = { fg = colors.markup_strikethrough, strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = colors.markup_heading, bold = true },
    ["@markup.heading.1"] = { fg = colors.markup_heading, bold = true },
    ["@markup.heading.2"] = { fg = colors.markup_heading, bold = true },
    ["@markup.heading.3"] = { fg = colors.markup_heading, bold = true },
    ["@markup.heading.4"] = { fg = colors.markup_heading, bold = true },
    ["@markup.heading.5"] = { fg = colors.markup_heading, bold = true },
    ["@markup.heading.6"] = { fg = colors.markup_heading, bold = true },
    ["@markup.quote"] = { fg = colors.markup_quote, italic = true },
    ["@markup.link"] = { fg = colors.markup_link, underline = true },
    ["@markup.link.label"] = { fg = colors.markup_link },
    ["@markup.link.url"] = { fg = colors.link, underline = true },
    ["@markup.raw"] = { fg = colors.markup_code, bg = colors.bg_alt },
    ["@markup.raw.block"] = { fg = colors.markup_code, bg = colors.bg_alt },
    ["@markup.list"] = { fg = colors.markup_list },
    ["@markup.list.checked"] = { fg = colors.semantic.success.base },
    ["@markup.list.unchecked"] = { fg = colors.fg_subtle },

    ["@diff.plus"] = { fg = colors.git_add, bg = colors.diff_add_bg },
    ["@diff.minus"] = { fg = colors.git_deleted, bg = colors.diff_remove_bg },
    ["@diff.delta"] = { fg = colors.git_modified, bg = colors.selection },

    ["@tag.tsx"] = { fg = colors.tag },
    ["@tag.javascript"] = { fg = colors.tag },
    ["@tag.typescript"] = { fg = colors.tag },

    ["@none"] = {},
    ["@conceal"] = { fg = colors.fg_subtle },

    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.punctuation"] = { link = "@punctuation" },

    ["@lsp.mod.deprecated"] = { strikethrough = true },
    ["@lsp.mod.readonly"] = { italic = true },
    ["@lsp.mod.static"] = { bold = true },
    ["@lsp.mod.abstract"] = { italic = true },
    ["@lsp.mod.async"] = { italic = true },

    ["@lsp.typemod.function.declaration"] = { link = "@function" },
    ["@lsp.typemod.function.definition"] = { link = "@function" },
    ["@lsp.typemod.method.declaration"] = { link = "@function.method" },
    ["@lsp.typemod.method.definition"] = { link = "@function.method" },
    ["@lsp.typemod.variable.declaration"] = { link = "@variable" },
    ["@lsp.typemod.variable.definition"] = { link = "@variable" },

    ["@lsp.type.selfParameter"] = { fg = colors.variable, italic = true },

    gitcommitSummary = { fg = colors.fg },
    gitcommitOverflow = { fg = colors.semantic.error.base },
    gitcommitHeader = { fg = colors.comment },
    gitcommitComment = { fg = colors.comment },
    gitcommitUntracked = { fg = colors.comment },
    gitcommitDiscarded = { fg = colors.comment },
    gitcommitSelected = { fg = colors.comment },
    gitcommitUnmerged = { fg = colors.semantic.warning.base },
    gitcommitOnBranch = { fg = colors.comment },
    gitcommitBranch = { fg = colors.func, bold = true },
    gitcommitDiscardedType = { fg = colors.keyword },
    gitcommitSelectedType = { fg = colors.keyword },
    gitcommitUntrackedFile = { fg = colors.string },
    gitcommitDiscardedFile = { fg = colors.string },
    gitcommitSelectedFile = { fg = colors.string },
    gitcommitUnmergedFile = { fg = colors.string },

    TelescopeNormal = { fg = colors.fg, bg = colors.bg_alt },
    TelescopeBorder = { fg = colors.border, bg = colors.bg_alt },
    TelescopePromptBorder = { fg = colors.border_focus, bg = colors.bg_alt },
    TelescopeResultsBorder = { fg = colors.border, bg = colors.bg_alt },
    TelescopePreviewBorder = { fg = colors.border, bg = colors.bg_alt },
    TelescopeSelection = { fg = colors.fg, bg = colors.selection, bold = true },
    TelescopeMatching = { fg = colors.cursor, bold = true },
    TelescopePromptPrefix = { fg = colors.cursor },
    TelescopePromptTitle = { fg = colors.fg, bg = colors.bg_alt, bold = true },
    TelescopeResultsTitle = { fg = colors.fg_subtle, bg = colors.bg_alt },
    TelescopePreviewTitle = { fg = colors.fg_subtle, bg = colors.bg_alt },

    NvimTreeNormal = { fg = colors.fg, bg = colors.bg_alt },
    NvimTreeEndOfBuffer = { fg = colors.bg_alt },
    NvimTreeRootFolder = { fg = colors.func, bold = true },
    NvimTreeFolderName = { fg = colors.fg },
    NvimTreeOpenedFolderName = { fg = colors.func },
    NvimTreeEmptyFolderName = { fg = colors.fg_subtle },
    NvimTreeIndentMarker = { fg = colors.border },
    NvimTreeVertSplit = { fg = colors.border },
    NvimTreeWindowPicker = { fg = colors.bg, bg = colors.cursor, bold = true },
    NvimTreeFileNew = { fg = colors.git_add },
    NvimTreeFileDeleted = { fg = colors.git_deleted },
    NvimTreeFileDirty = { fg = colors.git_modified },
    NvimTreeFileMerge = { fg = colors.git_conflict },
    NvimTreeFileStaged = { fg = colors.git_add },
    NvimTreeFileRenamed = { fg = colors.git_modified },
    NvimTreeFileIgnored = { fg = colors.git_ignored },
    NvimTreeGitNew = { fg = colors.git_add },
    NvimTreeGitDeleted = { fg = colors.git_deleted },
    NvimTreeGitDirty = { fg = colors.git_modified },
    NvimTreeGitStaged = { fg = colors.git_add },
    NvimTreeGitRenamed = { fg = colors.git_modified },
    NvimTreeGitIgnored = { fg = colors.git_ignored },

    WhichKey = { fg = colors.func },
    WhichKeyGroup = { fg = colors.keyword },
    WhichKeyDesc = { fg = colors.fg },
    WhichKeySeperator = { fg = colors.comment },
    WhichKeyFloat = { bg = colors.bg_alt },
    WhichKeyValue = { fg = colors.string },

    LazyNormal = { fg = colors.fg, bg = colors.bg_alt },
    LazyButton = { fg = colors.fg, bg = colors.bg },
    LazyButtonActive = { fg = colors.bg, bg = colors.cursor },
    LazyProgressTodo = { fg = colors.border },
    LazyProgressDone = { fg = colors.cursor },
    LazyCommit = { fg = colors.git_modified },
    LazyReasonKeys = { fg = colors.keyword },
    LazyReasonPlugin = { fg = colors.type },
    LazyReasonRuntime = { fg = colors.constant },
    LazyReasonEvent = { fg = colors.annotation },
    LazyReasonCmd = { fg = colors.func },
    LazyReasonFt = { fg = colors.string },
    LazyReasonImport = { fg = colors.annotation },
    LazyReasonSource = { fg = colors.type },

    MasonNormal = { fg = colors.fg, bg = colors.bg_alt },
    MasonHeader = { fg = colors.fg, bg = colors.bg_alt, bold = true },
    MasonHighlight = { fg = colors.cursor },
    MasonHighlightBlock = { fg = colors.bg, bg = colors.cursor },
    MasonHighlightBlockBold = { fg = colors.bg, bg = colors.cursor, bold = true },
    MasonMuted = { fg = colors.fg_subtle },
    MasonMutedBlock = { fg = colors.fg_subtle, bg = colors.bg },
    MasonMutedBlockBold = { fg = colors.fg_subtle, bg = colors.bg, bold = true },

    NoiceCmdline = { fg = colors.fg, bg = colors.bg_alt },
    NoiceCmdlineIcon = { fg = colors.cursor },
    NoiceCmdlinePopup = { fg = colors.fg, bg = colors.bg_alt },
    NoiceCmdlinePopupBorder = { fg = colors.border_focus, bg = colors.bg_alt },
    NoiceConfirm = { fg = colors.fg, bg = colors.bg_alt },
    NoiceConfirmBorder = { fg = colors.border_focus, bg = colors.bg_alt },
    NoicePopup = { fg = colors.fg, bg = colors.bg_alt },
    NoicePopupBorder = { fg = colors.border, bg = colors.bg_alt },
    NoiceScrollbar = { fg = colors.fg_subtle, bg = colors.border },
    NoiceScrollbarThumb = { fg = colors.fg_subtle },

    NotifyBackground = { bg = colors.bg },
    NotifyERRORBorder = { fg = colors.semantic.error.base },
    NotifyWARNBorder = { fg = colors.semantic.warning.base },
    NotifyINFOBorder = { fg = colors.semantic.info.base },
    NotifyDEBUGBorder = { fg = colors.comment },
    NotifyTRACEBorder = { fg = colors.primary.turquoise.base },
    NotifyERRORIcon = { fg = colors.semantic.error.base },
    NotifyWARNIcon = { fg = colors.semantic.warning.base },
    NotifyINFOIcon = { fg = colors.semantic.info.base },
    NotifyDEBUGIcon = { fg = colors.comment },
    NotifyTRACEIcon = { fg = colors.primary.turquoise.base },
    NotifyERRORTitle = { fg = colors.semantic.error.base },
    NotifyWARNTitle = { fg = colors.semantic.warning.base },
    NotifyINFOTitle = { fg = colors.semantic.info.base },
    NotifyDEBUGTitle = { fg = colors.comment },
    NotifyTRACETitle = { fg = colors.primary.turquoise.base },

    SnacksIndent = { fg = colors.border },
    SnacksIndentScope = { fg = colors.border_focus },
    SnacksPicker = { fg = colors.fg, bg = colors.bg_alt },
    SnacksPickerBorder = { fg = colors.border, bg = colors.bg_alt },
    SnacksPickerTitle = { fg = colors.fg, bg = colors.bg_alt, bold = true },
    SnacksPickerMatch = { fg = colors.cursor, bold = true },
    SnacksPickerDir = { fg = colors.fg_subtle },

    GitsignsAdd = { fg = colors.git_add },
    GitsignsChange = { fg = colors.git_modified },
    GitsignsDelete = { fg = colors.git_deleted },
    GitsignsAddNr = { fg = colors.git_add },
    GitsignsChangeNr = { fg = colors.git_modified },
    GitsignsDeleteNr = { fg = colors.git_deleted },
    GitsignsAddLn = { bg = colors.diff_add_bg },
    GitsignsChangeLn = { bg = colors.selection },
    GitsignsDeleteLn = { bg = colors.diff_remove_bg },

    IndentBlanklineChar = { fg = colors.border },
    IndentBlanklineContextChar = { fg = colors.border_focus },
    IndentBlanklineSpaceChar = { fg = colors.border },
    IndentBlanklineSpaceCharBlankline = { fg = colors.border },

    MiniIndentscopeSymbol = { fg = colors.border_focus },
    MiniIndentscopePrefix = { nocombine = true },

    LeapMatch = { fg = colors.cursor, bold = true, nocombine = true },
    LeapLabelPrimary = { fg = colors.bg, bg = colors.cursor, bold = true, nocombine = true },
    LeapLabelSecondary = { fg = colors.bg, bg = colors.semantic.warning.base, bold = true, nocombine = true },
    LeapBackdrop = { fg = colors.fg_subtle },

    FlashMatch = { fg = colors.cursor, bold = true },
    FlashCurrent = { fg = colors.bg, bg = colors.cursor, bold = true },
    FlashLabel = { fg = colors.bg, bg = colors.semantic.warning.base, bold = true },
    FlashBackdrop = { fg = colors.fg_subtle },

    CmpItemAbbr = { fg = colors.fg },
    CmpItemAbbrDeprecated = { fg = colors.fg_subtle, strikethrough = true },
    CmpItemAbbrMatch = { fg = colors.cursor, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = colors.cursor, bold = true },
    CmpItemKind = { fg = colors.type },
    CmpItemKindFunction = { fg = colors.func },
    CmpItemKindMethod = { fg = colors.method },
    CmpItemKindConstructor = { fg = colors.type },
    CmpItemKindClass = { fg = colors.class },
    CmpItemKindStruct = { fg = colors.type },
    CmpItemKindInterface = { fg = colors.interface },
    CmpItemKindModule = { fg = colors.namespace },
    CmpItemKindProperty = { fg = colors.property },
    CmpItemKindField = { fg = colors.property },
    CmpItemKindVariable = { fg = colors.variable },
    CmpItemKindConstant = { fg = colors.constant },
    CmpItemKindEnum = { fg = colors.type },
    CmpItemKindEnumMember = { fg = colors.constant },
    CmpItemKindKeyword = { fg = colors.keyword },
    CmpItemKindSnippet = { fg = colors.string },
    CmpItemKindColor = { fg = colors.primary.turquoise.base },
    CmpItemKindFile = { fg = colors.fg },
    CmpItemKindReference = { fg = colors.constant },
    CmpItemKindFolder = { fg = colors.func },
    CmpItemKindValue = { fg = colors.number },
    CmpItemKindEvent = { fg = colors.annotation },
    CmpItemKindOperator = { fg = colors.operator },
    CmpItemKindTypeParameter = { fg = colors.type },
    CmpItemMenu = { fg = colors.comment },

    BlinkCmpMenu = { fg = colors.fg, bg = colors.bg_alt },
    BlinkCmpMenuBorder = { fg = colors.border, bg = colors.bg_alt },
    BlinkCmpMenuSelection = { fg = colors.fg, bg = colors.selection },
    BlinkCmpLabel = { fg = colors.fg },
    BlinkCmpLabelMatch = { fg = colors.cursor, bold = true },
    BlinkCmpKind = { fg = colors.type },
    BlinkCmpSource = { fg = colors.comment },

    RainbowDelimiterRed = { fg = colors.semantic.error.base },
    RainbowDelimiterYellow = { fg = colors.semantic.warning.base },
    RainbowDelimiterBlue = { fg = colors.primary.blue.base },
    RainbowDelimiterOrange = { fg = colors.semantic.warning.dark },
    RainbowDelimiterGreen = { fg = colors.primary.green.base },
    RainbowDelimiterViolet = { fg = colors.primary.teal.base },
    RainbowDelimiterCyan = { fg = colors.primary.turquoise.base },
  }

  for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

function M.setup(opts)
  opts = opts or {}
  local variant = opts.variant or (vim.o.background == "dark" and "dark" or "light")
  local colors = palette[variant]
  vim.g.colors_name = "dma_theme"
  apply_highlights(colors)
end

return M